name: CI-CD Calidad de Software

on:
  push:
    branches: [ "develop", "main", "leonardo-ci-cd" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Compilar proyecto
        run: mvn clean compile

      - name: Ejecutar pruebas
        run: mvn test

      - name: Análisis PMD
        run: mvn pmd:check

      - name: Generar cobertura JaCoCo
        run: mvn verify

      - name: Subir reportes como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reportes-calidad
          path: target/site/jacoco/
